server {
listen 80;
resolver 127.0.0.11; 
location / {
proxy_pass http://frontend:80;
proxy_set_header Host $host;
}
location /api {
proxy_pass http://backend:3001;
proxy_set_header Host $host;
} 
}

